### ISSUE TITLE
Not quite understand the _bottleneck_loss function in the vdb.Losses.py

### ISSUE THREAD

**Issue by shengyuzhang** [akanimax/Variational_Discriminator_Bottleneck#1]
Hi, after reading your codes, I have the following questions:

1. Is mutual information the same as KL divergence and conditional entropy?

2. I googled "KL divergence python implementation", but didn't find something similar to your code. They look like something like the following:
`np.sum(np.where(p != 0, p * np.log(p / q), 0))`
So could you explain why you calc KL divergence using:
`kl_divergence = (0.5 * th.sum((mus ** 2) + (sigmas ** 2) - th.log((sigmas ** 2) + alpha) - 1, dim=1))`

or could you provide some relevant web links/blogs/videos explaining this?

Thanks in advance. :) BTW, your code is great, which is exactly what I am looking for.

**Comment by akanimax** [comment]
Hi @LightGal,

First of all, thank you for the compliments. They mean a lot to me. I have attempted to answer your questions as follows:

1.) No. Mutual Information is not the same as KL divergence and conditional entropy. For starters, Mutual Information is calculated between two different random variables X, Y while KL divergence is calculated between two distributions over the same random variable. Conditional entropy is just the entropy of a conditional probability distribution such as p(x | y), not sure why it is relevant here. 
Please refer to the **section 3. [equation (3) and (4)]** of the VDB paper in the literature folder to know about how the mutual information bottleneck is applied via a variational upper bound of the form `E[KL(z' || z)]`. Note it is the expected value of the KL divergence and not just KL divergence.

2.) you are right, `np.sum(np.where(p != 0, p * np.log(p / q), 0))` is the formula to compute the KL divergence between two distributions p and q over a discrete random variable. However, in our case we are calculating the KL divergence between two continuous Gaussian distributions over the latent variable z. [This](https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians) is the formula for calculating the KL divergence between two Gaussian distributions. Also note that you have to put the values `mu_2 = 0` and `sigma_2 = 1` in the formula because in our case the second distribution is the Standard Gaussian distribution. Little simplifying algebra will lead you to this equation `kl_divergence = (0.5 * th.sum((mus ** 2) + (sigmas ** 2) - th.log((sigmas ** 2) + alpha) - 1, dim=1))`. 

Hope this helps. 
Please let me know if you need any more info.

Cheers :beers:!
@akanimax

**Comment by shengyuzhang** [comment]
Thanks for your help. Your explanation is clear and instructive 👍.  I am new to these math concepts and formulas and surely I will then learn them all.
